### ISSUE TITLE
check only certain files/folder

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/repo-file-checker#11]
as discussed via mattermost:
use case: the files I'd like to ingest are spread over several folders, mixed with all kind of other files I do not care at all; therefore it would be nice to tell the filechecker, please only consider files following some naming convention, e.g. only files `*.tif`

**Comment by zozlak** [comment]
Implemented by bb9de7a405dcb943e873d19518b4d17cc7d72b82

It added the `--match regex` parameter. Only files/dirs matching the given regex are being checked. If a directory check is skipped, it's content is still being checked (but of course only files/subdirs matching the regex :-) ).
