### ISSUE TITLE
missing error msg

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/repo-file-checker#2]
if directories named in config.ini file don't exits the script just fails without any warning/error (at least a visible one in the std-out). Some warning/error msg written to the cmd-prompt/std-out e.g. "Directory {TEMP_DIR} does not exist, please create it an try again" would be nice

**Comment by zozlak** [comment]
Implemented by 72c408710f58ca9ff4defa19b119b4b2486a2ea3
